source 'https://github.com/CocoaPods/Specs.git'

target 'DRYLogging', :exclusive => true do
  pod "DRYLogging", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DRYLogging", :path => "../"
  pod "OCHamcrest"
  pod "OCMockito"
  pod "DRYTestUtilities"
end
