platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DRYLoggingExample' do
  pod "DRYLogging", :path => "../"

  target 'Tests' do
      inherit! :search_paths
      pod "OCHamcrest"
      pod "OCMockito"
      pod "DRYTestUtilities"
      pod "Quick"
      pod "Nimble"
  end
end
