source 'https://github.com/CocoaPods/Specs.git'

target 'DRYLogging' do
  pod "DRYLogging", :path => "../"
end

target 'Tests' do
  pod "DRYLogging", :path => "../"
  pod "OCHamcrest"
  pod "OCMockito"
  pod "DRYTestUtilities"
end
